"""Autoriser mêmes numéros par client, unique sur (client, numero, procedure)

Revision ID: 18df504bdd40
Revises: mettre_procedure_au_pluriel
Create Date: 2025-08-25 17:17:49.582230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18df504bdd40'
down_revision = 'mettre_procedure_au_pluriel'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.alter_column('procedures',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('uq_dossier_numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.create_index('uq_dossier_numero', ['numero'], unique=True)
        batch_op.alter_column('procedures',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
