"""Ajout colonne facture_id dans Timesheet

Revision ID: 39ccec2f50c4
Revises: 
Create Date: 2025-07-22 18:23:45.166476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ccec2f50c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facture_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('uk_facture_id', 'facture', ['facture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint('uk_facture_id', type_='foreignkey')
        batch_op.drop_column('facture_id')

    # ### end Alembic commands ###
