"""ajout motif dans attributionhistorique

Revision ID: 470a7b730155
Revises: fix_timesheet_heure_not_null
Create Date: 2025-08-20 19:15:41.039659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470a7b730155'
down_revision = 'fix_timesheet_heure_not_null'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribution_historique', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motif', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribution_historique', schema=None) as batch_op:
        batch_op.drop_column('motif')

    # ### end Alembic commands ###
