"""ajout nouvelles colonnes

Revision ID: 587bb4030744
Revises: 2c4fbcf60622
Create Date: 2025-09-29 10:49:52.967606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '587bb4030744'
down_revision = '2c4fbcf60622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_calendar_event_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('calendar_event_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('client_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('dossier_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheet_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('timesheet_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_suspended'), ['suspended'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_suspended'))
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('suspended_at')
        batch_op.drop_column('suspended')

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('timesheet_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_timesheet_user_id'))

    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dossier_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_dossier_user_id'))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('client_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_client_user_id'))

    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('calendar_event_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_calendar_event_user_id'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
