"""Ajout champ supprimé à toutes les tables

Revision ID: ea6ca4e43b2a
Revises: 8fdd871cd65a
Create Date: 2025-07-29 18:21:45.748283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6ca4e43b2a'
down_revision = '8fdd871cd65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supprimé', sa.Boolean(), nullable=True))

    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supprimé', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supprimé', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('supprimé')

    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.drop_column('supprimé')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('supprimé')

    # ### end Alembic commands ###
