"""ajout colonne description

Revision ID: eac9e65b3217
Revises: ea6ca4e43b2a
Create Date: 2025-08-04 22:33:53.013697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac9e65b3217'
down_revision = 'ea6ca4e43b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
